### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by subwolf** [CorruptComputer/ProtonDB-Tags#11]
I've seen errors saying I'm probably rate limited, after research I've found that normally up to 10,000 API requests can be made per day if you have your API key - I have 1,200 games.

Maybe wait a few seconds if there is an error?

**Comment by subwolf** [comment]
BTW I would be happy to come onboard to submit pull requests if you like.

**Comment by CorruptComputer** [comment]
Currently it's not multi-threaded, so waiting a second to try again might add quite a bit of time depending on the library. Currently I've seen that after around 200 requests the API starts returning `null`, so I would assume that is rate limiting. I want to see if there is a way to cache the results from the Steam API, as I don't foresee them changing a whole lot.

**Comment by RobLoach** [comment]
We could use the [exported ProtonDB Data](https://github.com/bdefore/protondb-data). It's in JSON format, and would save from having to make the HTTP requests.

**Comment by CorruptComputer** [comment]
That repo gets quite out of date, as so much can happen with Proton releases and that is only exported once a month. Also the rate limiting comes from the Steam API, rather than ProtonDB so I'm not sure how much it would help.

**Comment by subwolf** [comment]
The data source is https://protondb.max-p.me/ , which claims to update every 30 minutes. I see no reason you could not petition the owner to request data from it instead.

**Comment by Sickday** [comment]
Could you perhaps add a brief warning in the Readme to highlight that this issue occurs with larger libraries?

**Comment by debugrr** [comment]
Possible things to help: 
Give an option to retry the failed games only. 
Have it autowait (Fails, waits x seconds, tries again, fail, try again but wait longer to a limit, on success remove wait)

**Comment by subwolf** [comment]
@debugrr on the second note, perhaps add to a list to try again at the end of a script run.

**Comment by CorruptComputer** [comment]
Ok so it looks like the Steam API allows up to 100,000 calls per-day if you have an API key. Otherwise its 10 calls per 10 seconds. I can see if I can change it to only check the Steam API with a flag and add a 1 second wait to each lookup so it will only do 10 in the 10 seconds to stop from being rate limited.

**Comment by CorruptComputer** [comment]
I change the behavior in 90dd1a45907acb261a72580ab06b5e1b71b348fc as a temporary fix for this issue. Pulling from the Steam Store API will be opt-in now, as it adds 1 second wait per game to stop rate-limiting from occurring.

**Comment by subwolf** [comment]
Great change, will try it.

**Comment by subwolf** [comment]
1,221 games scanned without a hitch!

**Comment by subwolf** [comment]
If you choose to check for native support, I don't see an extra option in the list to specify a game as native - this would require a new category?

**Comment by CorruptComputer** [comment]
So I believe I may have at least partially mitigated this. The script will now cache the responses from the Steam API, which will greatly speed up subsequent runs. However this is more of a bandaid fix for now, I'm working on getting an API key for the project, however every API key I have gotten so far only works for the Steamworks API, not the Store API.

**Comment by subwolf** [comment]
It seems to be a permanent cache, maybe a future change could be to add an expiry date, say 3 months? BTW I also see that the entire cache is loaded and saved for each native check, when there are over 1,000 games to load/save each time, how does this affect performance, if at all?

**Comment by CorruptComputer** [comment]
It is, as the Steam Store listings do not change very often. I will be adding more choices in the future related to caching, including expiration and ProtonDB API caching as well. 

For myself the performance hit is negligible, I had originally made it save all at once rather than for each game. However testing with around 400+ games I noticed no difference in run speed with the current implementation. I went with this one due to a reduced complexity, makes future changes easier to work in.

**Comment by subwolf** [comment]
Excellent, you're building a great script. :)

**Comment by CorruptComputer** [comment]
Thanks! It really means a lot to hear so :smile:

**Comment by CorruptComputer** [comment]
The latest changes merged into the `dev` branch should improve this a bit. The caching is a lot more robust now, with the script caching info for a minimum of 7 days, with a random offset of 1-7 more days after that to avoid everything being checked at once. This should drastically reduce the number of API calls done by the script, and reduce the likelihood of being rate limited.
