### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by CorruptComputer** [CorruptComputer/ProtonDB-Tags#20]
I've been thinking that the name of this currently is a mouthful and maybe a better (shorter) name would be better. Any suggestions or opposition to changing the name of this project?

Please thumbs up/down to vote on suggestions below!

**Comment by Scotsguy** [comment]
Hmm, maybe ProtonDB-Classifer?

**Comment by CorruptComputer** [comment]
I just thought about this one as well: ProtonDB-Tags

**Comment by Sphiinx** [comment]
SteamifyProtonDB or ProtonDBSteamify?

Think as if you're taking ProtonDB and applying it to steam.

**Comment by PoorPocketsMcNewHold** [comment]
ProtonClassified. Because it classes games... depending on their proton compatibility.

**Comment by aTosser** [comment]
spdi - SteamProtonDatabaseIntegration alot easier to type spdi.py  (Also Speedy... see what I did there?)

**Comment by alexruetz** [comment]
I would go for ProtonTagsSteamTags or ProtonSteamTags

It uses the ProtonDB to tag games in Steam

**Comment by CorruptComputer** [comment]
I'll close the time for name submissions at the end of next Friday (July 12th). That will be just over 30 days for this issue to have been up. One week from then (Friday July 19th) will be the last day to vote. Whichever name suggested here has the most votes at that time will be chosen. I'll rename the script,  add a warning to the README, and after 30 (more) days I'll rename the repo as well to match.

I'll probably add a new repo with the previous name of this one as a heads up for if people have it bookmarked, as well as a script of the previous name with a heads up about the file name being changed.

**Comment by CorruptComputer** [comment]
Sorry for being a little late on this, I have been traveling and today is my first day back. It looks like, based on the votes, that ProtonDB-Tags has won. I will get everything changed later today when I am out of work. Thanks to everyone who made suggestions or voted!

**Comment by subwolf** [comment]
Great!

**Comment by CorruptComputer** [comment]
The repository has moved to its new name, sorry for the delay by a couple of days. I was out of town again!

**Comment by subwolf** [comment]
Sweet!
