### ISSUE TITLE
Error when trying to use --check-native

### ISSUE THREAD

**Issue by BeerGeekGamer** [CorruptComputer/ProtonDB-Tags#32]
When trying to run ProtonDB-Tag with `--check-native` argument, I get the following error

```
Steam found at: /home/beergeekgamer/.local/share/Steam/userdata
Found user 0: 19755583   BeerGeekGamer
Only one user found.
Selected: /home/beergeekgamer/.local/share/Steam/userdata/19755583/7/remote/sharedconfig.vdf
Steam native cache not found.
Creating Steam native cache...
Traceback (most recent call last):
  File "ProtonDB-Tags", line 299, in <module>
    main(ARGUMENTS)
  File "ProtonDB-Tags", line 230, in main
    if check_native and is_native(app_id):
  File "ProtonDB-Tags", line 53, in is_native
    with open(cache_path, 'w') as cache_file:
PermissionError: [Errno 13] Permission denied: './steamNativeCache.json'
```

**Comment by CorruptComputer** [comment]
Where do you have ProtonDB-Tags.py cloned to? This just looks to me like you don't have write permissions to the directory.

**Comment by BeerGeekGamer** [comment]
I'm running Manjaro with GNOME, and all I did was install it through the package manager. I'm new to Linux, so my knowledge is limited. When I run `python ProtonDB-Tags` it runs fine, just can't add options to the command.

**Comment by CorruptComputer** [comment]
Ah, well let me first say: Welcome to Linux friend!

This may be an issue with the permissions being set with the AUR package. I would like @ShayBox to take a look at this before I start making changes, as I have not read the AUR build script for this.

**Comment by ShayBox** [comment]
Looks like steamNativeCache.json is owned by another user, probably root, maybe you started steam as root, or maybe chown/chmodded the folder recursively by accident

**Comment by CorruptComputer** [comment]
@ShayBox `steamNativeCache.json` is created by the script. The file is in the same directory that the script is in. Depending on where the AUR build script clones the script to this may be somewhere that unprivileged users do not have access.

**Comment by ShayBox** [comment]
Ah, well that would be the problem, system packages are always installed into a system binary folder users have no access to writing to, and non binary files shouldn't go, so the script should be accessing a local user folder, the script should be following the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html) in this case, `$XDG_CACHE_HOME/protondb-tags/` with `$HOME/.cache/protondb-tags/` as a fallback if the env doesn't exist.

**Comment by CorruptComputer** [comment]
Sorry for no update on this for awhile. I'm still reading up on the XDG spec and how its different/better than just using `$HOME`. On my distro at least those vars don't even exist, so I'm not sure where they come from.

**Comment by ShayBox** [comment]
They're usually not set, it's a spec that relies on the fallbacks normally, it exists so users can move all of the stuff by setting them, instead of setting each programs config individually or sometimes no option at all.

**Comment by ShayBox** [comment]
If platform is Linux, If env exists, use env location, else, use specified fallback by spec.
Would be the easiest way to explain it in pseudocode.
Some programs don't impliment xdg correctly (they don't read env, only hardcoded fallback), so if you set the env they won't use it, there's a list somewhere on the archwiki of program!s that don't follow xdg.

**Comment by CorruptComputer** [comment]
@BeerGeekGamer @ShayBox Would you be able to test the latest commit in the dev branch to see if it fixes this properly?

**Comment by ShayBox** [comment]
I never had the problem myself, but the code looks good, hopefully that fixes the problem
