### ISSUE TITLE
Add native tag also

### ISSUE THREAD

**Issue by tomas02061991** [CorruptComputer/ProtonDB-Tags#36]
It would be nice if the script could add a native tag, to all games running natively on linux as well

**Comment by CorruptComputer** [comment]
Please read the README of the repo:

> By default this will not check the Steam API for native titles. This can be enabled with the `--check-native` flag. This will add a 1 second wait to each Steam API call, as without this you will get rate-limited. The script will build a cache of these as it runs, so after the first run it will go faster.
