### ISSUE TITLE
There is no sharedconfig.vdf file in my ~/.steam/ folder anymore

### ISSUE THREAD

**Issue by DoubyCz** [CorruptComputer/ProtonDB-Tags#37]
This tool is was amazing, but it's not working with new steam version.

There is no sharedconfig.vdf file in ~/.steam/ directory anymore. There is ony registry.vdf.

OS: Ubuntu 20.04 LTS
Steam Client: build 2020-06-04 05:51:01 (1591251555)

**Comment by DoubyCz** [comment]
Only workaround I found is "firefox steam://resetcollections" terminal command ... which forces steam to import old categories into new collections format - and this workaround works great, but ...

your script ProtonDB-Tags.py uses default browser for this, but this is problem, because only firefox can handle it right. If someone has opera or chrome browser set as default, this little trick doesn't work.

**Comment by CorruptComputer** [comment]
The second issue you mentioned should be fixed when 1.1.1 is released later today. However I'm still not sure about the first `sharedconfig.vdf` issue you mentioned.

**Comment by CorruptComputer** [comment]
Thanks for reporting these issues! I'm going to close this since I haven't heard anything back about the first issue, and the second issue should already be fixed. 

Please feel free to re-open and let me know if you are still having this issue.
