### ISSUE TITLE
Getting various Python Errors when Running

### ISSUE THREAD

**Issue by TheKarion** [CorruptComputer/ProtonDB-Tags#42]
Traceback (most recent call last):
  File "/home/domglusk/gitcloned/ProtonDB-Tags/ProtonDB-Tags.py", line 8, in <module>
    import vdf
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/__init__.py", line 19, in <module>
    from vdf.vdict import VDFDict
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/vdict.py", line 9, in <module>
    class _kView(_c.KeysView):
AttributeError: module 'collections' has no attribute 'KeysView'

These are the errors. The requirements are met, that was confirmed by the requirements command. Don't know if its an Arch thing or what. Any possible solution? This is from the github version NOT the aur version (as the aur version also gives an error)

**Comment by Technetium1** [comment]
Unfortunately this has been broken for a while. See https://github.com/CorruptComputer/ProtonDB-Tags/issues/33

**Comment by CorruptComputer** [comment]
Hi, thank you for bringing this issue to my attention! Could you try the latest changes in the `dev` branch and let me know if that fixes this error for you?

**Comment by TheKarion** [comment]
Alright will do, would you suggest using the AUR version or compile from github?

**Comment by Technetium1** [comment]
@TheKarion [protondb-tags-dev-git](https://aur.archlinux.org/packages/protondb-tags-dev-git) is the only one that uses the dev branch :eyes:

**Comment by TheKarion** [comment]
How would I run the requirements.txt from the aur version? Or does it do it automatically. Right now I'm getting this
Traceback (most recent call last):
  File "/usr/bin/ProtonDB-Tags", line 8, in <module>
    import vdf
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/__init__.py", line 19, in <module>
    from vdf.vdict import VDFDict
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/vdict.py", line 9, in <module>
    class _kView(_c.KeysView):
AttributeError: module 'collections' has no attribute 'KeysView'

**Comment by CorruptComputer** [comment]
I would not recommend the AUR version to test this, as I am not the maintainer of it and I do not know if it has been updated.

Instead you can just git checkout the dev branch here and run this command to install the new requirements versions:
```
pip install -r requirements.txt
```

**Comment by TheKarion** [comment]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pylint==2.5.3 in /home/domglusk/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.5.3)
Requirement already satisfied: requests==2.24 in /home/domglusk/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.24.0)
Requirement already satisfied: vdf==3.3 in /home/domglusk/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (3.3)
Requirement already satisfied: astroid<=2.5,>=2.4.0 in /home/domglusk/.local/lib/python3.10/site-packages (from pylint==2.5.3->-r requirements.txt (line 1)) (2.5)
Requirement already satisfied: isort<5,>=4.2.5 in /home/domglusk/.local/lib/python3.10/site-packages (from pylint==2.5.3->-r requirements.txt (line 1)) (4.3.21)
Requirement already satisfied: mccabe<0.7,>=0.6 in /home/domglusk/.local/lib/python3.10/site-packages (from pylint==2.5.3->-r requirements.txt (line 1)) (0.6.1)
Requirement already satisfied: toml>=0.7.1 in /home/domglusk/.local/lib/python3.10/site-packages (from pylint==2.5.3->-r requirements.txt (line 1)) (0.10.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/domglusk/.local/lib/python3.10/site-packages (from requests==2.24->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/domglusk/.local/lib/python3.10/site-packages (from requests==2.24->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/domglusk/.local/lib/python3.10/site-packages (from requests==2.24->-r requirements.txt (line 2)) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.10/site-packages (from requests==2.24->-r requirements.txt (line 2)) (2022.6.15)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in /home/domglusk/.local/lib/python3.10/site-packages (from astroid<=2.5,>=2.4.0->pylint==2.5.3->-r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: wrapt<1.13,>=1.11 in /home/domglusk/.local/lib/python3.10/site-packages (from astroid<=2.5,>=2.4.0->pylint==2.5.3->-r requirements.txt (line 1)) (1.12.1)



Traceback (most recent call last):
  File "/home/domglusk/ProtonDB-Tags/ProtonDB-Tags.py", line 8, in <module>
    import vdf
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/__init__.py", line 19, in <module>
    from vdf.vdict import VDFDict
  File "/home/domglusk/.local/lib/python3.10/site-packages/vdf/vdict.py", line 9, in <module>
    class _kView(_c.KeysView):
AttributeError: module 'collections' has no attribute 'KeysView'

**Comment by CorruptComputer** [comment]
@TheKarion That stack trace is not from the `dev` branch. The versions of the dependencies listed there are the old ones.

**Comment by TheKarion** [comment]
Steam found at: /home/domglusk/.local/share/Steam/userdata
Found user 0: 235144203   TheKarion
Found user 1: anonymous   (Could not load username from Steam)
Which user number would you like to open? 0
Selected: /home/domglusk/.local/share/Steam/userdata/235144203/7/remote/sharedconfig.vdf
Traceback (most recent call last):
  File "/home/domglusk/gitcloned/ProtonDB-Tags/ProtonDB-Tags.py", line 343, in <module>
    main(ARGUMENTS)
  File "/home/domglusk/gitcloned/ProtonDB-Tags/ProtonDB-Tags.py", line 247, in main
    apps = get_apps_list(sharedconfig, fetch_games)
  File "/home/domglusk/gitcloned/ProtonDB-Tags/ProtonDB-Tags.py", line 86, in get_apps_list
    apps_list = sharedconfig[configstore][software][valve][steam][apps]
UnboundLocalError: local variable 'apps' referenced before assignment

**Comment by CorruptComputer** [comment]
Ah no worries, thanks for checking again!

If possible could you zip up and attach the `sharedconfig.vdf` file you have? 
This would help me to identify what is going on here, as it seems like the apps section of your file doesn't exist based on the error you sent.

This file would be located here for you, based off the info you gave above: `/home/domglusk/.local/share/Steam/userdata/235144203/7/remote/sharedconfig.vdf`

**Comment by TheKarion** [comment]
Alright awesome thanks, I'll give it a shot and share the results

**Comment by TheKarion** [comment]
[sharedconfig.vdf.zip](https://github.com/CorruptComputer/ProtonDB-Tags/files/9050381/sharedconfig.vdf.zip)

Update! Steam is opening and it's confirming if I want to reset my collections and import the old ones, but the only one that imports is lutris w/ VTMB (which I downloaded through lutris on gog), and had it create a steam shortcut for me. 
Here's the output:

Steam found at: /home/domglusk/.local/share/Steam/userdata
Found user 0: 235144203   TheKarion
Found user 1: anonymous   (Could not load username from Steam)
Which user number would you like to open? 0
Selected: /home/domglusk/.local/share/Steam/userdata/235144203/7/remote/sharedconfig.vdf
Found 0 Steam games
WARNING: This may clear your current tags on Steam!
Would you like to save sharedconfig.vdf? (y/N)y
Please launch Steam, then press Enter to continue...
steam.sh[44481]: Running Steam on endeavouros rolling 64-bit
steam.sh[44481]: STEAM_RUNTIME is enabled automatically
setup.sh[44555]: Steam runtime environment up-to-date!
steam.sh[44481]: Steam client's requirements are satisfied
ERROR: ld.so: object '/usr/${LIB}/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by CorruptComputer** [comment]
Ah great! Looks like the script is working for you now. Though unfortunately your games aren't being found due to #33, sadly there isn't any great solutions for this. You can add the `--fetch-games` option to the script, which should fetch your games list from the Steam API. 

The problem with this option, is that any newly 'found' games by the script will have their tags cleared due to limitations on the info that Steam is willing to give through the API. As far as I have been able to tell, there is no way to read your current tags from the Steam API.

**Comment by TheKarion** [comment]
Alright went through the interaction, 
Steam found at: /home/domglusk/.local/share/Steam/userdata
Found user 0: 235144203   TheKarion
Found user 1: anonymous   (Could not load username from Steam)
Which user number would you like to open? 0
Selected: /home/domglusk/.local/share/Steam/userdata/235144203/7/remote/sharedconfig.vdf
There was a problem retreiving your games list fromt the Steam API, please check the Steam API key and Steam ID you provided.
Found 0 Steam games
WARNING: This may clear your current tags on Steam!
Would you like to save sharedconfig.vdf? (y/N)y
Please launch Steam, then press Enter to continue...
steam.sh[8108]: Running Steam on endeavouros rolling 64-bit
steam.sh[8108]: STEAM_RUNTIME is enabled automatically
setup.sh[8182]: Steam runtime environment up-to-date!
steam.sh[8108]: Steam client's requirements are satisfied
ERROR: ld.so: object '/usr/${LIB}/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

This is on the second time.

**Comment by CorruptComputer** [comment]
Are you sure that your Steam API key and Steam ID are correct there? I also just realized that the changes don't provide any way to change those after the first time they are set, so I'll need to add an option for that as well.

Thank you for testing these changes, and I'm sorry that you have to keep testing and testing again. I'll let you know when those changes are made, but I'm going to take a small break from this script today since I have some other stuff I need to get done.

**Comment by TheKarion** [comment]
I'm always happy to help. How would I change the api and steam id then?

**Comment by CorruptComputer** [comment]
Thanks for your understanding!

If you delete your local config file the script should re-prompt you to enter that info.
This config will be located in one of these two locations, depending on if you have `$XDG_CONFIG_HOME` set.
  - `$XDG_CONFIG_HOME/ProtonDB-Tags/config.json`
  - `$HOME/.config/ProtonDB-Tags/config.json`

I also have some changes planned to make this a bit more automatic and try to give more info on which value specifically is causing the Steam API to error out. 

As well as making it so that the API key you enter is not shown as you type or copy/paste it, similar to how sudo works when entering your password as an extra security measure there. I realized when reading your message from before that someone may want to copy/paste that info here, and having that be shown might be problematic. So thanks for helping fix another issue!

**Comment by TheKarion** [comment]
![Screenshot_20220707_152222](https://user-images.githubusercontent.com/64805993/177864894-f122b4b2-857d-439e-9923-da3c022be783.png)
Perfect! So the steamid was a really long number, and not your friend code as I first thought. If it doesn't work deleting the $XDG_CONFIG_HOME/ProtonDB-Tags/config.json file allowed me to restart and then it worked just fine

**Comment by TheKarion** [comment]
Should I go ahead and mark the AUR package as out of date?

**Comment by CorruptComputer** [comment]
Not quite yet, I haven't released the new version. Have a couple small issues to fix, but should be released later tonight.

I can go ahead and mark it out of date once it's been released though, thanks for checking!
