### ISSUE TITLE
Support flatpak Steam

### ISSUE THREAD

**Issue by masytan** [CorruptComputer/ProtonDB-Tags#49]
Glad to see this active again, thanks for your work!
On Silverblue with only flatpak Steam installed, the new version throws the error "sh: line 1: steam: command not found" after pressing enter at "Please launch Steam, then press Enter to continue...". The old version had the same problem, but threw a bunch more errors.
It still works fine by manually using steam://resetcollections in my browser, so this is just a minor inconvenience.

**Comment by CorruptComputer** [comment]
Thanks for bringing this issue to my attention, I had thought the script already supported Flatpak and didn't realize there was this issue.

I just installed Fedora Silverblue on a laptop of mine to test this real quick and I should have a solution for this within the next day or so.

**Comment by CorruptComputer** [comment]
So it looks like `flatpak run com.valvesoftware.Steam steam://resetcollections` works sometimes. Though most of the time this will just launch a second instance of Steam, not quite sure why it works sometimes but not other times.

Whatever the case is, it looks like that same issue also happens with directly calling `xdg-open steam://resetcollections`, so I don't think there is going to be a way to automatically.

I did find that putting this URL in your browser works well, but I would be afraid to directly call a browser from the script as there could be any number of browsers that someone might have installed. So for now the best we might be able to do is just give a click-able link in the command line output that you can use to open it in your browser.

**Comment by masytan** [comment]
I seem to be getting reliable results opening steam with `xdg-open steam://nav/library` or `xdg-open steam://open/games`, then using `xdg-open steam://resetcollections`, if that helps. I get the problem you describe when opening steam normally.
The link solution would suit me fine, anyway.

**Comment by CorruptComputer** [comment]
Oh nice! I just tested a bit and yeah it looks like if the script is what launches the Flatpak then the `steam://resetcollections` command will work perfectly.

If possibly could you check out the `flatpak-test` branch of this repo and make sure this is working for you? 
I was able to get this working on my Fedora Silverblue installation very reliably, but want to make sure it works for you as well.

**Comment by masytan** [comment]
I tested, and can confirm that it works! Thank you very much.
