### ISSUE TITLE
Tags not appearing

### ISSUE THREAD

**Issue by realunkn0wn** [CorruptComputer/ProtonDB-Tags#51]
i restarted steam and rerun the script now a few times but after resetting my collections there are no tags

`Steam found at: /home/sk3nn1x/.local/share/Steam/userdata
Found user 0: 250071477   sk3nn1x
Only one user found.
Selected: /home/sk3nn1x/.local/share/Steam/userdata/250071477/7/remote/sharedconfig.vdf

Found a total of 216 Steam games.
Processed (10 of 216) games...
Processed (20 of 216) games...
Processed (30 of 216) games...
Processed (40 of 216) games...
Processed (50 of 216) games...
Processed (60 of 216) games...
Processed (70 of 216) games...
Processed (80 of 216) games...
Processed (90 of 216) games...
Processed (100 of 216) games...
Processed (110 of 216) games...
Processed (120 of 216) games...
Processed (130 of 216) games...
Processed (140 of 216) games...
Processed (150 of 216) games...
Processed (160 of 216) games...
Processed (170 of 216) games...
Processed (180 of 216) games...
Processed (190 of 216) games...
Processed (200 of 216) games...
Processed (210 of 216) games...
`

**Comment by CorruptComputer** [comment]
Hey there, thanks for reaching out! Just to confirm, was your issue resolved?

**Comment by realunkn0wn** [comment]
yes u should update ur requirements on github cuz i just installed requests and vdf xD after using the requierements.txt it worked

**Comment by CorruptComputer** [comment]
Requests and vdf are the only two requirements for running the script, was there something else that was missing for you?

**Comment by realunkn0wn** [comment]
pylint

**Comment by realunkn0wn** [comment]
but it worked after i installed pylint? xD

**Comment by realunkn0wn** [comment]
ah no: Installing collected packages: wrapt, tomlkit, mccabe, lazy-object-proxy, isort, dill, charset-normalizer, requests, astroid, pylint
Successfully installed astroid-2.11.7 charset-normalizer-2.1.0 dill-0.3.5.1 isort-5.10.1 lazy-object-proxy-1.7.1 mccabe-0.7.0 pylint-2.14.4 requests-2.28.1 tomlkit-0.11.1 wrapt-1.14.1

**Comment by realunkn0wn** [comment]
after that it worked but idk how he picket up the other things

**Comment by CorruptComputer** [comment]
From the output you showed in the original post, the script ran just fine.

Did you happen to restart Steam between runs there? There is a bug in the Steam client where it won't actually read the updated file sometimes and it can be fixed by restarting Steam.

**Comment by realunkn0wn** [comment]
i restarted steam like 5 times but i think it was that i didnt selected group by collection
