### ISSUE TITLE
Python3 only

### ISSUE THREAD

**Issue by subwolf** [CorruptComputer/ProtonDB-Tags#8]
Not everyone is running Python V3 by default yet, see https://pythonclock.org/ - my Linux Mint install still runs V2.7. Please add a note to the readme.md stating to use python3 if not the default.

**Comment by Krafting** [comment]
I was about to create the same "issue".

here is how I "fixed" it.

```
sudo apt install python3
sudo apt install python3-pip
sudo pip3 install vdf
```

then run the script

**Comment by subwolf** [comment]
I did similar.

**Comment by CorruptComputer** [comment]
Ah, this is a good point. Thanks for letting me know! I haden't thought of others not having Python3 by default and will definitely make a note of it in the README!

**Comment by S0litaire** [comment]
Roughly the same issue ( have python 2.7 & 3 installed)
I had to run :
'python3 ./ProtonDB-to-Steam-Library.py'
as 'python' defaulted to using 2.7.

**Comment by CorruptComputer** [comment]
This has been added to the README: https://github.com/CorruptComputer/ProtonDB-to-Steam-Library/blob/master/README.md#dependencies

Going to leave this open in case anyone else has this issue.

**Comment by subwolf** [comment]
Perfect.

**Comment by tntexplosivesltd** [comment]
It actually runs with Python 2.7 perfectly fine.

**Comment by tntexplosivesltd** [comment]
If the script is made executable, you don't need to run it with python and the shebang explicitly specifies python3 so it should work properly:
`./ProtonDB-to-Steam-Library.py`

**Comment by CorruptComputer** [comment]
I believe this can be closed now that python2 is dead. Long live the python3 king.

But on a serious note, are there still distros that are including python2 by default now that it is no longer maintained?

**Comment by Krafting** [comment]
> I believe this can be closed now that python2 is dead. Long live the python3 king.
> 
> But on a serious note, are there still distros that are including python2 by default now that it is no longer maintained?

Well I hope every distro will switch to python3, but i'm on Mint 19.3 and the default is still python 2.7.17
Also, you could maybe just add a section in the README.md so you can close the issue ?

**Comment by CorruptComputer** [comment]
There is already a notice in the README about python3 being required:
![image](https://user-images.githubusercontent.com/5573038/73790509-35055680-4766-11ea-9660-20e0833dac3b.png)

**Comment by Krafting** [comment]
My bad! then I guess you can close this, yes :)

**Comment by CorruptComputer** [comment]
Closing this due to Python 2 now being EOL, and most distros will release with Python 3 by default now.
